### ISSUE TITLE
Add opacity slider for user to be able to change opacity on any georeferenced maps in the viewer

### ISSUE THREAD

**Issue by emilyrbowe** [allmaps/allmaps#11]

**Comment by coret** [comment]
+1  The ability to adjust the opacity of the georeferenced map in order to check the accuracy is often asked by the Gouda Timemachine volunteers.

**Comment by bertspaan** [comment]
You can already do this in the development version of Allmaps Viewer: https://dev.viewer.allmaps.org/

**Comment by bertspaan** [comment]
https://viewer.allmaps.org/ now has an opacity control.
