### ISSUE TITLE
Allow modern map pane of Editor to accept an arbitrary tile layer as base

### ISSUE THREAD

**Issue by garrettdashnelson** [allmaps/allmaps#14]
Feature request: it would be great if it were possible to swap out the default OSM-based modern map in Editor for anything with a XYZ or TileJSON endpoint. I know that it is already possible to switch into a satellite view mode, but oftentimes it would be helpful to have a different layer. I'm particularly thinking about georeferencing one historic map against another already-georeferenced historic map in cases where the modern landscape has changed dramatically and obliterated useful referencing features. However, I can also imagine that there are occasionally good local-scale contemporary basemap services that might aid in precise editing.

**Comment by bertspaan** [comment]
When I have time + funding for a bigger update of Allmaps Editor, this is one of the first things on my list. For now, I've added a function that you can call from the browser's console:

```js
setUserBaseMapUrl('https://tile.openstreetmap.org/{z}/{x}/{y}.png')
```

I've just pushed this to https://dev.editor.allmaps.org, I'll do a few tests and then push it to https://editor.allmaps.org.

**Comment by sammeltassen** [comment]
It's live now and the alternative base map can also be loaded with the url parameter `userBaseMapUrl=`. See this notebook for an explanation and examples: https://observablehq.com/d/f97e823615ea778c
