### ISSUE TITLE
Chrome Crashes using MapLibre with Raster Tile Styles/Layers

### ISSUE THREAD

**Issue by jayvarner** [allmaps/allmaps#142]
I've noticed that Chrome crashes while zooming/panning a map when a raster style/layer is present. I can only reproduce this in Chrome. The crash still occurs in incognito mode and with all extensions disabled. I also tried it on a fresh install of Chromium. The Chromium logs show this error:

```
[4680:259:0919/152655.462366:FATAL:webgl_image_conversion.cc(3325)] Check failed: false.
0   Chromium Framework                  0x0000000121e20f92 ChromeMain + 94122738
...
16  Chromium Framework                  0x000000011ee8555e ChromeMain + 44202174
Crash keys:
  "devtools_present" = "true"
  "max_scheduler_idle_tasks" = "0"
  "max_idle_tasks" = "0"
  "loaded-origin-0" = "https://cdpn.io"
  "web-frame-count" = "1"
  "gpu-glver" = "OpenGL ES 2.0.0 (ANGLE 2.1.23894 git hash: b98e6bc07e88)"
  "gpu-generation-intel" = "9"
  "gpu-vsver" = "1.00"
  "gpu-psver" = "1.00"
  "gpu_count" = "2"
  "gpu-devid" = "0x3e9b"
  "gpu-venid" = "0x8086"
  "renderer_foreground" = "true"
  "v8_ro_space_firstpage_address" = "0xca500000000"
  "v8_isolate_address" = "0x13c001d0000"
  "variations" = "e61ea..."
  "num-experiments" = "407"
  "reentry_guard_tls_slot" = "266"
  "switch-15" = "--seatbelt-client=120"
  "switch-14" = "--variations-seed-version"
  "switch-13" = "--field-trial-handle=1718379636,r,3780538116447773437,7670625343"
  "switch-12" = "--metrics-shmem-handle=1752395122,r,8783189758453539804,17224880"
  "switch-11" = "--shared-files"
  "switch-10" = "--launch-time-ticks=1000365831306"
  "switch-9" = "--time-ticks-at-unix-epoch=-1725773567508574"
  "switch-8" = "--renderer-client-id=11"
  "switch-7" = "--enable-main-frame-before-activation"
  "switch-6" = "--enable-gpu-memory-buffer-compositor-resources"
  "switch-5" = "--enable-zero-copy"
  "switch-4" = "--num-raster-threads=4"
  "switch-3" = "--lang=en-US"
  "switch-2" = "--file-url-path-alias=/gen=/Applications/gen"
  "switch-1" = "--start-stack-profiler"
  "num-switches" = "18"
  "osarch" = "x86_64"
  "pid" = "4680"
  "ptype" = "renderer"
```

Here are some examples:

- [Error with base style with raster layer](https://codepen.io/jayvarner/pen/gONVjdw?editors=0010). Sometimes, you have to zoom in and out with the WarpedMapLayer in view (Rotterdam) for a few.
- [NO error when base style only has vector layers](https://codepen.io/jayvarner/pen/poXMOeq?editors=0010)
- [Error with vector base style but WMS layer present](https://codepen.io/jayvarner/pen/gONVZOm?editors=0010)

This is what it looks like for me (and others I've asked to test):

![allmaps_error](https://github.com/user-attachments/assets/0294ee69-db54-4506-bba1-1e35829e9284)

Apologies if this is known and has been discussed. I couldn't find any issues that seemed related. I also understand that this may not specifically be an issue with Allmaps - given it only happens with Chrome.

Safari actually does log an error in the console, but doesn't crash.

```
WebGL: INVALID_OPERATION: texImage2D: Invalid format/type combination.
```

As best as I can tell, that error is coming [from here](https://github.com/allmaps/allmaps/blob/7f64be8fa02a5c94487a21a09800ef5c10031f51/packages/render/src/WebGL2Renderer.ts#L828-L838).

I'm using a MacBook Pro. I had someone confirm it happens on Windows. It also happens on my Android device.

**Comment by bertspaan** [comment]
Hey @jayvarner, thanks for reporting this bug. WebGL is difficult to test and debug, things work slightly different across browsers/OSes/GPUs.

We're working on an improved version of Allmaps' render module (which powers the plugins for Leaflet/OL/MapLibre), you can see it in action on dev.viewer.allmaps.org, we've fixed most of the caching/flickering issues. We haven't published new versions of the different modules on npm yet. Maybe this new version fixes this issue?

I can reproduce the error you reported locally, so I can also see what happens when I use new render module. I'll try that today and I'll report back here.

**Comment by bertspaan** [comment]
This bug still occurs in our new render code, unfortunately.

I did find out that if I make the Chrome window smaller, things work fine. And if I make the window slightly smaller, the bug still occurs, but later in during zooming in. 

Probably some WebGL memory thing? Maybe we're creating textures that are too large? But things seem to work OK with the OpenLayers plugin, I haven't seen this error there. 

@mclaeysb, do you have ideas?

**Comment by bertspaan** [comment]
I'll try to find out what causes Chrome's "Aw, Snap!" error: https://superuser.com/questions/607563/how-to-determine-what-is-causing-chrome-to-show-the-aw-snap-dialogue

<img width="62" alt="image" src="https://github.com/user-attachments/assets/b525d728-57c3-4420-8ea0-312d1124115a">

**Comment by mclaeysb** [comment]
Thanks a lot for reporting this @jayvarner ! Will look in to this too.

**Comment by bertspaan** [comment]
I've had a look at Chrome's debug log by starting Chrome like this (I'm using [Chrome Canary](https://www.google.com/intl/nl/chrome/canary/):

```sh
open -a "Google Chrome Canary" --args --enable-logging
```

Then I can read the logs like this:

```sh
tail -f /Users/bertspaan/Library/Application Support/Google/Chrome Canary/chrome_debug.log
```

When I zoom in/out slowly, I see errors like this:

```
[86267:259:0920/120654.273592:ERROR:gl_utils.cc(422)] [.WebGL-0x1140041af00] GL_INVALID_OPERATION: Vertex buffer is not big enough for the draw call
[86255:259:0920/120654.273836:INFO:CONSOLE(0)] "[.WebGL-0x1140041af00] GL_INVALID_OPERATION: Vertex buffer is not big enough for the draw call", source: http://localhost:5513/test/bug.html (0)
```

They occur every now and then, but they don't make Chrome crash.

However, every time Chrome _does_ crash, this error comes up:

```
[86293:259:0920/120657.663170:FATAL:check.cc(361)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
```

Not a very helpful error message. Can't find anything by googling this error.

**Comment by bertspaan** [comment]
@mclaeysb, we could try fixing the `Vertex buffer is not big enough for the draw call` errors, probably wouldn't hurt

**Comment by bertspaan** [comment]
But I don't think that solves this issue. Sometimes, Chrome crashes, I see the `Check failed: false.` error in the logs but I don't see any `Vertex buffer is not big enough for the draw call` errors.

**Comment by bertspaan** [comment]
I'm debugging `WebGL2WarpedMap.ts`, it seems Chrome crashes during the [`gl.texImage2D` call on line 379](https://github.com/allmaps/allmaps/blob/develop/packages/render/src/maps/WebGL2WarpedMap.ts#L379).

**Comment by bertspaan** [comment]
OK I think I've fixed it.

**Comment by bertspaan** [comment]
Not sure yet, but seems to have something to do with the `cachedTilesResourcePositionsAndDimensions` texture with the `RGBA_INTEGER` format. Each pixel in that texture is a vec4 with 4 integers. Somehow, there's something about that texture that Chrome doesn't like. When I change that texture's format to `RED_INTEGER` (each pixel is a single integer), I make the texture's length 4 times as big to make the same number of integers fit, and I update the shader to read the values from that texture in a slightly different way, everything still works. But no more "Aw, snap!"

**Comment by bertspaan** [comment]
Fun.

**Comment by bertspaan** [comment]
OK, @mclaeysb, I can push those changes to the `improve-render` branch and you can maybe have a look?

**Comment by jayvarner** [comment]
@bertspaan and @mclaeysb, y'all are amazing. Thanks for looking into this and for Allmaps in general. This is a really fun useful project. I'll stay tuned for updates. Again, I really appreciate your work.

**Comment by bertspaan** [comment]
Thanks @jayvarner! I can publish a new version of the Allmaps MapLibre plugin to npm next week. Or let me know if you're in a hurry, then I can probably do it today or tomorrow.

**Comment by bertspaan** [comment]
@mclaeysb, see  https://github.com/allmaps/allmaps/commit/b0949ed15167975e66e4364427a1ddebddb3aa7d.

**Comment by jayvarner** [comment]
@bertspaan next week is totally fine. Thank you for the quick response.

**Comment by bertspaan** [comment]
Hey @jayvarner, we've decided to fix a few more things in Allmaps' render module before we publish a new version so it's taking a bit longer.
