### ISSUE TITLE
Request: Opacity slider for Leaflet plugin

### ISSUE THREAD

**Issue by dgplacenames** [allmaps/allmaps#144]
[Leaflet.Control.Opacity](https://github.com/dayjournal/Leaflet.Control.Opacity) doesn't work with warpedMapLayer. Can we get something similar for the Leaflet plugin? It would save having to use XYZ tiles which do work with Leaflet.Control.Opacity.

**Comment by sammeltassen** [comment]
The `warpedMapLayer` does support changing the opacity as follows:

```js
warpedMapLayer.setOpacity(0.5)
```

See the [documentation](https://github.com/allmaps/allmaps/tree/main/packages/leaflet#setopacity) which follows the Leaflet [GridLayer API](https://leafletjs.com/reference.html#gridlayer). So you can make your own slider to make this work ([here's an example](https://observablehq.com/@allmaps/leaflet-plugin)).

Perhaps it's the plugin that needs to be adapted to support warpedMapLayers? Can you create an issue there?

**Comment by dgplacenames** [comment]
Thank you. Yes, I'll create an issue there.
