### ISSUE TITLE
"Rotate image" option would be useful for scans that are not oriented ^North^

### ISSUE THREAD

**Issue by mapninja** [allmaps/allmaps#171]
I'm trying to georeference a very old map of campus, but it's oriented ^South^ which is making the task more difficult. If I could rotate the iiif image to match the reference map, that would be really useful. 

<img width="2055" alt="image" src="https://github.com/user-attachments/assets/ccdfd1c7-3caa-4ac8-adf0-d34a8b39ae06">

**Comment by sammeltassen** [comment]
Shift + option/alt + drag should work in both panes!
