### ISSUE TITLE
Feature Requested: Showing the masked areas in the Allmaps viewer

### ISSUE THREAD

**Issue by xlicl** [allmaps/allmaps#38]
Currently, users can see the masked areas in the Allmaps editor. Is there any way to see the masked areas in the Appmaps viewer? Enabling the visibility of masked areas could be beneficial as it would allow users to identify the specific information that has been omitted or hidden. 
Thanks!

**Comment by bertspaan** [comment]
Yes this is a feature of the new version I'm working on! Soon!

**Comment by xlicl** [comment]
great! thanks!
