### ISSUE TITLE
Presentation 3 Manifests from Internet Archive showing as invalid

### ISSUE THREAD

**Issue by garrettdashnelson** [allmaps/allmaps#60]
Manifests from the new Presentation API 3 service at Internet Archive are not parsing in Allmaps Editor.

Two examples:

https://iiif.archive.org/iiif/3/sprunermenkeatla00spru/manifest.json

https://iiif.archive.org/iiif/3/masterhighwaypla00char/manifest.json

Both of these do validate in https://presentation-validator.iiif.io

I am not super familiar yet with Presentation 3, so I'm out on a wild guess here looking at it very briefly, but I _think_ it's because some of the `Image` children of the `items` element do not have `body` or dimensional attributes?

**Comment by bertspaan** [comment]
Thanks for reporting! This is a bug in Allmaps' IIIF parser, I'll fix it right away. Updating Allmaps Editor will take me a little longer, I'll have time probably next week!

**Comment by bertspaan** [comment]
@garrettdashnelson Just updated Allmaps Editor.

See https://editor.allmaps.org/?#/mask?url=https%3A%2F%2Fiiif.archive.org%2Fiiif%2F3%2Fsprunermenkeatla00spru%2Fmanifest.json&image=0acba1442291939c and https://viewer.allmaps.org/?url=https%3A%2F%2Fannotations.allmaps.org%2Fimages%2F0acba1442291939c

**Comment by bertspaan** [comment]
And https://viewer.allmaps.org/?url=https%3A%2F%2Fannotations.allmaps.org%2Fimages%2Fb95da4eddb6ba49d !!!

<img width="1245" alt="image" src="https://github.com/allmaps/allmaps/assets/1194896/4883f7f1-2221-4ebd-8633-1586c9172acf">

**Comment by garrettdashnelson** [comment]
Amazing! 

It seems like there may still be some hiccups with the annotation server cross-referencing between manifests and images? For instance, working with https://iiif.archive.org/iiif/3/masterhighwaypla00char/manifest.json, the annotation server seems to think the Manifest hash id should be `8c925e3c469c5991` but [that's not returning anything](https://annotations.allmaps.org/manifests/8c925e3c469c5991). 

I've added masks and gcps to two images within that Manifest, which are persisting in Editor, so Editor must be identifying them correctly.

**Comment by bertspaan** [comment]
I guess that's caused by the fact that, if you open h https://iiif.archive.org/iiif/3/masterhighwaypla00char/manifest.json. the ID of the manifest is https://iiif.archive.org/iiif/masterhighwaypla00char/manifest.json (without the `3`). Allmaps always uses the ID from the manifests (and images) itself. However, this causes problems sometimes... Don't know if there's an easy solution.

**Comment by bertspaan** [comment]
Yes! I have not yet updated Allmaps Viewer to use the latest IIIF parser. It'll work when you load the annotation directly. That's next on my to do list.
