### ISSUE TITLE
Rendering in dev Viewer not serving some tiles on deeper zooms 

### ISSUE THREAD

**Issue by itspangler** [allmaps/allmaps#90]
I've been running into this lately and just wanted to flag it. No matter how long I linger on a zoom level, sometimes the tiles for a warped image don't seem to load:

![Recording 2024-03-08 at 12 23 22](https://github.com/allmaps/allmaps/assets/39773984/227087b7-5426-4107-a490-b97d00dc0485)

**Comment by bertspaan** [comment]
@mclaeysb I added a try/catch block before calling the `triangulate` function, see https://github.com/allmaps/allmaps/commit/77948a879e3fdd77de37b9f3a95420ba731d7dde. Sometimes rendering stopped when one of the maps could not be triangulated properly. We should make something that fixes common errors in masks (e.g. duplicate points) before triangulating.

Maybe this fixes your error, @itspangler ?

**Comment by mclaeysb** [comment]
Good idea! It's best to do this in the @allmaps/annotation package, not in triangulate, so it's also applied everywhere else in rendering. You can use the `conformPolygon()` function in the @allmaps/stdlib to filter out duplicated points!
